# Desktop AI Job Runtime Contracts — adapter.py
#
# Abstract runtime adapter interface and a fake implementation
# that simulates job execution for demonstration purposes.

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from pathlib import Path

from .contracts import (
    ArtifactKind,
    JobArtifact,
    JobStatus,
    RuntimeAdapterInfo,
    RuntimeCapability,
)
from .manifest import JobManifest
from .trace import ExecutionTrace


class BaseRuntimeAdapter(ABC):
    """Abstract base class for runtime adapters.

    Subclasses implement the actual AI execution logic.
    """

    @abstractmethod
    def get_info(self) -> RuntimeAdapterInfo:
        ...

    @abstractmethod
    def run(self, manifest: JobManifest, trace: ExecutionTrace) -> JobManifest:
        ...


class FakeRuntimeAdapter(BaseRuntimeAdapter):
    """A fake adapter that simulates job execution.

    - Updates manifest status through PENDING -> RUNNING -> SUCCEEDED
    - Records trace events at each stage
    - Creates fake preview and log artifacts with real placeholder files
    - Does NOT perform any real AI inference
    """

    def get_info(self) -> RuntimeAdapterInfo:
        return RuntimeAdapterInfo(
            adapter_id="fake-adapter-001",
            name="FakeRuntimeAdapter",
            version="1.0.0",
            capabilities=[
                RuntimeCapability.LOCAL_EXECUTION,
                RuntimeCapability.DRY_RUN,
                RuntimeCapability.TRACE_EVENTS,
            ],
        )

    def run(self, manifest: JobManifest, trace: ExecutionTrace) -> JobManifest:
        output_path = Path(manifest.output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        manifest.status = JobStatus.RUNNING
        trace.add_event("adapter_started", "FakeRuntimeAdapter started execution.")

        trace.add_event("input_scanned", f"Scanned {len(manifest.inputs)} input(s).")

        preview_artifact = JobArtifact(
            artifact_id=uuid.uuid4().hex[:12],
            kind=ArtifactKind.PREVIEW,
            path=str(output_path / "fake_preview.txt"),
            media_type="text/plain",
        )
        (output_path / "fake_preview.txt").write_text(
            f"Fake preview for job {manifest.job_id}\\nGenerated by FakeRuntimeAdapter.\\n",
            encoding="utf-8",
        )

        log_artifact = JobArtifact(
            artifact_id=uuid.uuid4().hex[:12],
            kind=ArtifactKind.LOG,
            path=str(output_path / "fake_run.log"),
            media_type="text/plain",
        )
        (output_path / "fake_run.log").write_text(
            f"[{uuid.uuid4().hex[:8]}] FakeRuntimeAdapter run log for {manifest.job_id}\\n"
            f"  adapter_started -> input_scanned -> artifact_created -> adapter_finished\\n",
            encoding="utf-8",
        )

        trace.add_event("artifact_created", f"Created {len(manifest.artifacts) + 2} artifact(s).")

        manifest.artifacts.extend([preview_artifact, log_artifact])
        manifest.status = JobStatus.SUCCEEDED

        trace.add_event("adapter_finished", f"Job {manifest.job_id} finished with status {manifest.status}.")

        return manifest
